### ISSUE TITLE
poll verification fails after creation, as not indexed by mdw

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-governance#145]

**Comment by mradkov** [comment]
Is this why this message appears:

![05cb3e7e-3172-4368-8664-5de43743422e](https://user-images.githubusercontent.com/13139371/88280265-2861c400-ccee-11ea-862d-097712846a99.png)

**Comment by thepiwo** [comment]
it is, but suppressing the error message is not a solution here

**Comment by kenodressel** [comment]
I guess we should just make it less intrusive? also we should differenciate between we can not verify the poll correctness and we almost certainly know its not correct.

**Comment by thepiwo** [comment]
yes, either this or have a more reliable way to fetch contract bytecode

**Comment by kenodressel** [comment]
Any suggestions on a more reliable way? I guess we could save the contractCreateTxHash from the previous step and temporarily use it in the local storage for querying the TX directly from the node

**Comment by thepiwo** [comment]
For the creator of the poll we can disable the check when the referral to the poll comes from the create page. Your suggestion is also fine. Or a new feature in the core could allow us to easily fetch the needed bytecode.

**Comment by kenodressel** [comment]
The question is how urgent is this issue, as a new core feature would probably take some time. I could also think of a middle ground as we can expect that this issue only appears in the first minutes of a poll being created. Basically make the warning in this case less intrusive (eg. integrate it into the site) and have it say "We can not verify this poll right now, please try again in a few minutes" and keep the current approach for polls where we know the bytecode does not match.
